# Generated by Django 4.2.11 on 2025-07-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
